# Generated by Django 5.1 on 2024-08-11 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200, unique=True)),
                ('c_image', models.ImageField(default=None, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=200)),
                ('pkkh', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('p_image', models.ImageField(default=None, null=True, upload_to='images')),
                ('catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('total', models.FloatField(editable=False)),
                ('created_date', models.DateTimeField()),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.catagory')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.product')),
            ],
        ),
    ]
