# Generated by Django 5.1 on 2024-08-13 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_customer_categories_customer_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='c_image',
            field=models.ImageField(upload_to='images', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='c_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_name',
            field=models.CharField(max_length=200, verbose_name='customer name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.catagory', verbose_name='catagory name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.customer', verbose_name='cus tomer name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.product', verbose_name=' product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.ImageField(upload_to='images', verbose_name='product image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='product name'),
        ),
    ]
