# Generated by Django 5.1 on 2024-08-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_catagory_c_image_alter_product_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='c_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='category image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='product image'),
        ),
    ]
