# Generated by Django 5.1 on 2024-08-14 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_catagory_c_image_alter_product_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catagory', verbose_name='catagory name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customer', verbose_name='cus tomer name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name=' product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.catagory'),
        ),
    ]
