# Generated by Django 5.1 on 2024-08-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_order_catagory_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='c_name',
            field=models.CharField(max_length=200, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(max_length=200, verbose_name='product name'),
        ),
    ]
